# Generated by Django 2.2.6 on 2020-03-12 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disorder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HPOToDisorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hp', models.CharField(max_length=32)),
                ('term', models.CharField(max_length=256)),
                ('freq', models.IntegerField()),
                ('disorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml.Disorder')),
            ],
        ),
    ]
